version: '3.8'

services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/project
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql8-service
        networks:
            - nginx-php82-mysql8
    php82-service:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: php82-container
        expose:
            - "9000"
        volumes:
            - ./:/var/www/project
        networks:
            - nginx-php82-mysql8
        depends_on:
            - mysql8-service
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mintos
            MYSQL_USER: mintos
            MYSQL_PASSWORD: mintos
        networks:
            - nginx-php82-mysql8
networks:
  nginx-php82-mysql8:
    driver: bridge
